import { useState, useRef } from "react";
import { ChromePicker } from "react-color";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Slider } from "@/components/ui/slider";
import { ChevronDown, Plus, Minus, Bold, Italic, Underline, Upload, X } from "lucide-react";
import { Toggle } from "@/components/ui/toggle";
import { Switch } from "@/components/ui/switch";

export interface TextElementConfig {
  id: string;
  type: 'headline' | 'subheadline' | 'feature' | 'cta';
  text: string;
  position: 'top-left' | 'top-center' | 'top-right' | 'center-left' | 'center' | 'center-right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
  fontSize: number;
  color: string;
  fontFamily: string;
  fontWeight: 'normal' | 'bold';
  fontStyle: 'normal' | 'italic';
  textDecoration: 'none' | 'underline';
  backgroundColor?: string;
  icon?: string;
}

export interface LogoConfig {
  file: File | null;
  url: string | null;
  position: 'top-left' | 'top-center' | 'top-right' | 'center-left' | 'center-right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
  size: number;
  enabled: boolean;
}

interface AdTextConfigProps {
  elements: TextElementConfig[];
  onElementsChange: (elements: TextElementConfig[]) => void;
  logoConfig: LogoConfig;
  onLogoConfigChange: (config: LogoConfig) => void;
  ctaEnabled: boolean;
  onCtaEnabledChange: (enabled: boolean) => void;
}

const GOOGLE_FONTS = [
  "Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Oswald", 
  "Poppins", "Raleway", "Playfair Display", "Merriweather",
  "Source Sans Pro", "Ubuntu", "Nunito", "Rubik", "Work Sans",
  "PT Sans", "Lora", "Fira Sans", "Quicksand", "Mulish",
  "Bebas Neue", "Anton", "Permanent Marker", "Pacifico", "Dancing Script"
];

const POSITION_OPTIONS = [
  { value: "top-left", label: "Top Left" },
  { value: "top-center", label: "Top Center" },
  { value: "top-right", label: "Top Right" },
  { value: "center-left", label: "Center Left" },
  { value: "center", label: "Center" },
  { value: "center-right", label: "Center Right" },
  { value: "bottom-left", label: "Bottom Left" },
  { value: "bottom-center", label: "Bottom Center" },
  { value: "bottom-right", label: "Bottom Right" },
];

const LOGO_POSITION_OPTIONS = [
  { value: "top-left", label: "Top Left" },
  { value: "top-center", label: "Top Center" },
  { value: "top-right", label: "Top Right" },
  { value: "center-left", label: "Center Left" },
  { value: "center-right", label: "Center Right" },
  { value: "bottom-left", label: "Bottom Left" },
  { value: "bottom-center", label: "Bottom Center" },
  { value: "bottom-right", label: "Bottom Right" },
];

// Icons will be generated by AI based on feature text

const FONT_SIZES = [12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 48, 56, 64, 72];

const AdTextConfig = ({ elements, onElementsChange, logoConfig, onLogoConfigChange, ctaEnabled, onCtaEnabledChange }: AdTextConfigProps) => {
  const logoInputRef = useRef<HTMLInputElement>(null);
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({
    headline: true,
    subheadline: true,
    features: true,
    cta: true,
    logo: true,
  });

  const updateElement = (id: string, updates: Partial<TextElementConfig>) => {
    onElementsChange(elements.map(el => el.id === id ? { ...el, ...updates } : el));
  };


  const addFeature = () => {
    // Get settings from first feature if exists, otherwise use defaults
    const existingFeatures = elements.filter(el => el.type === 'feature');
    const firstFeature = existingFeatures[0];
    
    const newFeature: TextElementConfig = {
      id: `feature-${Date.now()}`,
      type: 'feature',
      text: '',
      position: firstFeature?.position || 'bottom-center',
      fontSize: firstFeature?.fontSize || 16,
      color: firstFeature?.color || '#ffffff',
      fontFamily: firstFeature?.fontFamily || 'Inter',
      fontWeight: firstFeature?.fontWeight || 'normal',
      fontStyle: firstFeature?.fontStyle || 'normal',
      textDecoration: firstFeature?.textDecoration || 'none',
    };
    onElementsChange([...elements, newFeature]);
  };

  const removeFeature = (id: string) => {
    onElementsChange(elements.filter(el => el.id !== id));
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const url = URL.createObjectURL(file);
      onLogoConfigChange({ ...logoConfig, file, url });
    }
  };

  const removeLogo = () => {
    if (logoConfig.url) {
      URL.revokeObjectURL(logoConfig.url);
    }
    onLogoConfigChange({ ...logoConfig, file: null, url: null });
  };

  // Update all features with the same style settings
  const updateAllFeaturesStyle = (updates: Partial<TextElementConfig>) => {
    onElementsChange(elements.map(el => 
      el.type === 'feature' ? { ...el, ...updates } : el
    ));
  };

  // Simple feature editor - just text + remove button (icons generated by AI)
  const renderFeatureEditor = (element: TextElementConfig) => (
    <div key={element.id} className="flex items-center gap-2 p-2 bg-muted/50 rounded-lg">
      <Input
        placeholder="Enter feature text"
        value={element.text}
        onChange={(e) => updateElement(element.id, { text: e.target.value })}
        className="h-8"
      />
      <Button
        variant="ghost"
        size="icon"
        className="shrink-0 h-8 w-8"
        onClick={() => removeFeature(element.id)}
      >
        <Minus className="h-4 w-4" />
      </Button>
    </div>
  );

  // Shared feature style settings editor
  const renderFeatureStyleSettings = () => {
    const firstFeature = featureElements[0];
    if (!firstFeature) return null;

    return (
      <div className="space-y-3 p-3 bg-muted/30 rounded-lg border border-border/50 mb-3">
        <Label className="text-xs text-muted-foreground">Style (applies to all features)</Label>
        
        <div className="grid grid-cols-2 gap-2">
          {/* Position */}
          <div className="space-y-1">
            <Label className="text-xs">Position</Label>
            <Select
              value={firstFeature.position}
              onValueChange={(v) => updateAllFeaturesStyle({ position: v as TextElementConfig['position'] })}
            >
              <SelectTrigger className="h-8">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {POSITION_OPTIONS.map(opt => (
                  <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Font Size */}
          <div className="space-y-1">
            <Label className="text-xs">Size</Label>
            <Select
              value={String(firstFeature.fontSize)}
              onValueChange={(v) => updateAllFeaturesStyle({ fontSize: Number(v) })}
            >
              <SelectTrigger className="h-8">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {FONT_SIZES.map(size => (
                  <SelectItem key={size} value={String(size)}>{size}px</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Font Family */}
        <div className="space-y-1">
          <Label className="text-xs">Font</Label>
          <Select
            value={firstFeature.fontFamily}
            onValueChange={(v) => updateAllFeaturesStyle({ fontFamily: v })}
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="max-h-[200px]">
              {GOOGLE_FONTS.map(font => (
                <SelectItem key={font} value={font} style={{ fontFamily: font }}>
                  {font}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Style Toggles & Color */}
        <div className="flex items-center gap-2 flex-wrap">
          <Toggle
            size="sm"
            pressed={firstFeature.fontWeight === 'bold'}
            onPressedChange={(p) => updateAllFeaturesStyle({ fontWeight: p ? 'bold' : 'normal' })}
          >
            <Bold className="h-4 w-4" />
          </Toggle>
          <Toggle
            size="sm"
            pressed={firstFeature.fontStyle === 'italic'}
            onPressedChange={(p) => updateAllFeaturesStyle({ fontStyle: p ? 'italic' : 'normal' })}
          >
            <Italic className="h-4 w-4" />
          </Toggle>
          <Toggle
            size="sm"
            pressed={firstFeature.textDecoration === 'underline'}
            onPressedChange={(p) => updateAllFeaturesStyle({ textDecoration: p ? 'underline' : 'none' })}
          >
            <Underline className="h-4 w-4" />
          </Toggle>

          <Popover>
            <PopoverTrigger asChild>
              <Button variant="outline" size="sm" className="gap-2">
                <div
                  className="w-4 h-4 rounded border"
                  style={{ backgroundColor: firstFeature.color }}
                />
                Color
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <ChromePicker
                color={firstFeature.color}
                onChange={(color) => updateAllFeaturesStyle({ color: color.hex })}
                disableAlpha
              />
            </PopoverContent>
          </Popover>
        </div>
      </div>
    );
  };

  const renderTextElementEditor = (element: TextElementConfig, showRemove = false, _isCta = false) => (
    <div key={element.id} className="space-y-3 p-3 bg-muted/50 rounded-lg">

      <div className="grid grid-cols-2 gap-2">
        {/* Position */}
        <div className="space-y-1">
          <Label className="text-xs">Position</Label>
          <Select
            value={element.position}
            onValueChange={(v) => updateElement(element.id, { position: v as TextElementConfig['position'] })}
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {POSITION_OPTIONS.map(opt => (
                <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Font Size */}
        <div className="space-y-1">
          <Label className="text-xs">Size</Label>
          <Select
            value={String(element.fontSize)}
            onValueChange={(v) => updateElement(element.id, { fontSize: Number(v) })}
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FONT_SIZES.map(size => (
                <SelectItem key={size} value={String(size)}>{size}px</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Font Family */}
      <div className="space-y-1">
        <Label className="text-xs">Font</Label>
        <Select
          value={element.fontFamily}
          onValueChange={(v) => updateElement(element.id, { fontFamily: v })}
        >
          <SelectTrigger className="h-8">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="max-h-[200px]">
            {GOOGLE_FONTS.map(font => (
              <SelectItem key={font} value={font} style={{ fontFamily: font }}>
                {font}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Style Toggles & Color */}
      <div className="flex items-center gap-2 flex-wrap">
        <Toggle
          size="sm"
          pressed={element.fontWeight === 'bold'}
          onPressedChange={(p) => updateElement(element.id, { fontWeight: p ? 'bold' : 'normal' })}
        >
          <Bold className="h-4 w-4" />
        </Toggle>
        <Toggle
          size="sm"
          pressed={element.fontStyle === 'italic'}
          onPressedChange={(p) => updateElement(element.id, { fontStyle: p ? 'italic' : 'normal' })}
        >
          <Italic className="h-4 w-4" />
        </Toggle>
        <Toggle
          size="sm"
          pressed={element.textDecoration === 'underline'}
          onPressedChange={(p) => updateElement(element.id, { textDecoration: p ? 'underline' : 'none' })}
        >
          <Underline className="h-4 w-4" />
        </Toggle>

        <Popover>
          <PopoverTrigger asChild>
            <Button variant="outline" size="sm" className="gap-2">
              <div
                className="w-4 h-4 rounded border"
                style={{ backgroundColor: element.color }}
              />
              Text
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-auto p-0" align="start">
            <ChromePicker
              color={element.color}
              onChange={(color) => updateElement(element.id, { color: color.hex })}
              disableAlpha
            />
          </PopoverContent>
        </Popover>

        {element.type === 'cta' && (
          <Popover>
            <PopoverTrigger asChild>
              <Button variant="outline" size="sm" className="gap-2">
                <div
                  className="w-4 h-4 rounded border"
                  style={{ backgroundColor: element.backgroundColor || '#10b981' }}
                />
                Button
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <ChromePicker
                color={element.backgroundColor || '#10b981'}
                onChange={(color) => updateElement(element.id, { backgroundColor: color.hex })}
                disableAlpha
              />
            </PopoverContent>
          </Popover>
        )}
      </div>

    </div>
  );

  const headline = elements.find(el => el.type === 'headline');
  const subheadline = elements.find(el => el.type === 'subheadline');
  const cta = elements.find(el => el.type === 'cta');
  const featureElements = elements.filter(el => el.type === 'feature');

  return (
    <div className="space-y-3">
      {/* Headline */}
      {headline && (
        <Collapsible open={openSections.headline} onOpenChange={(o) => setOpenSections(s => ({ ...s, headline: o }))}>
          <CollapsibleTrigger className="flex items-center justify-between w-full p-2 rounded-md hover:bg-muted">
            <span className="font-medium text-sm">Headline</span>
            <ChevronDown className={`h-4 w-4 transition-transform ${openSections.headline ? 'rotate-180' : ''}`} />
          </CollapsibleTrigger>
          <CollapsibleContent className="pt-2">
            <div className="space-y-2">
              <Input
                placeholder="Enter headline"
                value={headline.text}
                onChange={(e) => updateElement(headline.id, { text: e.target.value })}
              />
              {renderTextElementEditor(headline)}
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}

      {/* Subheadline */}
      {subheadline && (
        <Collapsible open={openSections.subheadline} onOpenChange={(o) => setOpenSections(s => ({ ...s, subheadline: o }))}>
          <CollapsibleTrigger className="flex items-center justify-between w-full p-2 rounded-md hover:bg-muted">
            <span className="font-medium text-sm">Subheadline</span>
            <ChevronDown className={`h-4 w-4 transition-transform ${openSections.subheadline ? 'rotate-180' : ''}`} />
          </CollapsibleTrigger>
          <CollapsibleContent className="pt-2">
            <div className="space-y-2">
              <Input
                placeholder="Enter subheadline (optional)"
                value={subheadline.text}
                onChange={(e) => updateElement(subheadline.id, { text: e.target.value })}
              />
              {renderTextElementEditor(subheadline)}
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}

      {/* Features */}
      <Collapsible open={openSections.features} onOpenChange={(o) => setOpenSections(s => ({ ...s, features: o }))}>
        <CollapsibleTrigger className="flex items-center justify-between w-full p-2 rounded-md hover:bg-muted">
          <span className="font-medium text-sm">Features ({featureElements.length})</span>
          <ChevronDown className={`h-4 w-4 transition-transform ${openSections.features ? 'rotate-180' : ''}`} />
        </CollapsibleTrigger>
        <CollapsibleContent className="pt-2 space-y-2">
          {renderFeatureStyleSettings()}
          {featureElements.map(feature => renderFeatureEditor(feature))}
          <Button variant="outline" size="sm" onClick={addFeature} className="w-full">
            <Plus className="h-4 w-4 mr-2" /> Add Feature
          </Button>
        </CollapsibleContent>
      </Collapsible>

      {/* CTA */}
      {cta && (
        <div className="space-y-2">
          <div className="flex items-center justify-between p-2 rounded-md hover:bg-muted">
            <div className="flex items-center gap-3">
              <span className="font-medium text-sm">Call to Action</span>
              <Switch
                checked={ctaEnabled}
                onCheckedChange={onCtaEnabledChange}
              />
            </div>
            {ctaEnabled && (
              <button
                type="button"
                onClick={() => setOpenSections(s => ({ ...s, cta: !s.cta }))}
                className="p-1 rounded hover:bg-muted-foreground/10"
              >
                <ChevronDown className={`h-4 w-4 transition-transform ${openSections.cta ? 'rotate-180' : ''}`} />
              </button>
            )}
          </div>
          {ctaEnabled && openSections.cta && (
            <div className="space-y-2 pl-2">
              <Input
                placeholder="Enter CTA text"
                value={cta.text}
                onChange={(e) => updateElement(cta.id, { text: e.target.value })}
              />
              {renderTextElementEditor(cta, false, true)}
            </div>
          )}
        </div>
      )}

      {/* Logo */}
      <div className="space-y-2">
        <div className="flex items-center justify-between p-2 rounded-md hover:bg-muted">
          <div className="flex items-center gap-3">
            <span className="font-medium text-sm">Logo</span>
            <Switch
              checked={logoConfig.enabled}
              onCheckedChange={(enabled) => onLogoConfigChange({ ...logoConfig, enabled })}
            />
          </div>
          {logoConfig.enabled && (
            <button
              type="button"
              onClick={() => setOpenSections(s => ({ ...s, logo: !s.logo }))}
              className="p-1 rounded hover:bg-muted-foreground/10"
            >
              <ChevronDown className={`h-4 w-4 transition-transform ${openSections.logo ? 'rotate-180' : ''}`} />
            </button>
          )}
        </div>
        {logoConfig.enabled && openSections.logo && (
          <div className="space-y-3 p-3 bg-muted/50 rounded-lg">
            <input
              ref={logoInputRef}
              type="file"
              accept="image/*"
              onChange={handleLogoUpload}
              className="hidden"
            />
            
            {logoConfig.url ? (
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <img
                    src={logoConfig.url}
                    alt="Logo preview"
                    className="w-16 h-16 object-contain bg-white rounded border"
                  />
                  <div className="flex-1">
                    <p className="text-sm text-muted-foreground">Logo uploaded</p>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={removeLogo}
                      className="text-destructive hover:text-destructive"
                    >
                      <X className="h-4 w-4 mr-1" />
                      Remove
                    </Button>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <Label className="text-xs">Position</Label>
                  <Select
                    value={logoConfig.position}
                    onValueChange={(v) => onLogoConfigChange({ ...logoConfig, position: v as LogoConfig['position'] })}
                  >
                    <SelectTrigger className="h-8">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {LOGO_POSITION_OPTIONS.map(opt => (
                        <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label className="text-xs">Size: {logoConfig.size}px</Label>
                  <Slider
                    value={[logoConfig.size]}
                    onValueChange={([size]) => onLogoConfigChange({ ...logoConfig, size })}
                    min={30}
                    max={150}
                    step={5}
                    className="w-full"
                  />
                </div>
              </div>
            ) : (
              <Button
                variant="outline"
                onClick={() => logoInputRef.current?.click()}
                className="w-full"
              >
                <Upload className="h-4 w-4 mr-2" />
                Upload Logo
              </Button>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AdTextConfig;