export type Gender = "female" | "male" | "kids";
export type AgeGroup = "adult" | "child";
export type Ethnicity = "European" | "African" | "Middle Eastern" | "East Asian" | "South Asian" | "Latin American" | "Mixed";
export type AgeCategory = "1 – 2.5" | "7 – 13" | "13 – 18" | "20 – 30" | "30 – 50" | "50 – 65" | "65+";
export type BodyType = "Slim" | "Athletic" | "Average" | "Curvy" | "Overweight" | "Plus size";
export type UseCase = "Fashion" | "E-commerce" | "Lifestyle";

export interface ModelData {
  id: string;
  url: string;
  preview: string;
  name: string;
  gender: Gender;
  ageGroup: AgeGroup;
  ethnicity: Ethnicity;
  ageCategory?: AgeCategory;
  bodyType?: BodyType;
  useCase?: UseCase;
}

export const getDefaultModels = (baseUrl: string, cacheBuster: string): ModelData[] => [
  { id: "model-3", url: `${baseUrl}/models/model-3.png?${cacheBuster}`, preview: `/models/model-3.png?${cacheBuster}`, name: "Adrian", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-4", url: `${baseUrl}/models/model-4.png?${cacheBuster}`, preview: `/models/model-4.png?${cacheBuster}`, name: "Aisha", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-93", url: `${baseUrl}/models/model-103.png?${cacheBuster}`, preview: `/models/model-103.png?${cacheBuster}`, name: "Ama", gender: "female", ageGroup: "adult", ethnicity: "African" },
  { id: "model-5", url: `${baseUrl}/models/model-5.png?${cacheBuster}`, preview: `/models/model-5.png?${cacheBuster}`, name: "Amal", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-91", url: `${baseUrl}/models/model-101.png?${cacheBuster}`, preview: `/models/model-101.png?${cacheBuster}`, name: "Amara", gender: "female", ageGroup: "adult", ethnicity: "African" },
  { id: "model-6", url: `${baseUrl}/models/model-6.png?${cacheBuster}`, preview: `/models/model-6.png?${cacheBuster}`, name: "Amelia", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-7", url: `${baseUrl}/models/model-7.png?${cacheBuster}`, preview: `/models/model-7.png?${cacheBuster}`, name: "Anil", gender: "male", ageGroup: "adult", ethnicity: "South Asian" },
  { id: "model-8", url: `${baseUrl}/models/model-8.png?${cacheBuster}`, preview: `/models/model-8.png?${cacheBuster}`, name: "Ava", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-10", url: `${baseUrl}/models/model-20.png?${cacheBuster}`, preview: `/models/model-20.png?${cacheBuster}`, name: "Bas", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-11", url: `${baseUrl}/models/model-21.png?${cacheBuster}`, preview: `/models/model-21.png?${cacheBuster}`, name: "Benjamin", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-95", url: `${baseUrl}/models/model-105.png?${cacheBuster}`, preview: `/models/model-105.png?${cacheBuster}`, name: "Camila", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-12", url: `${baseUrl}/models/model-22.png?${cacheBuster}`, preview: `/models/model-22.png?${cacheBuster}`, name: "Carlos", gender: "male", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-13", url: `${baseUrl}/models/model-23.png?${cacheBuster}`, preview: `/models/model-23.png?${cacheBuster}`, name: "Charlotte", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-14", url: `${baseUrl}/models/model-24.png?${cacheBuster}`, preview: `/models/model-24.png?${cacheBuster}`, name: "Chen", gender: "male", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-15", url: `${baseUrl}/models/model-25.png?${cacheBuster}`, preview: `/models/model-25.png?${cacheBuster}`, name: "Chloe", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-16", url: `${baseUrl}/models/model-26.png?${cacheBuster}`, preview: `/models/model-26.png?${cacheBuster}`, name: "Clara", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-17", url: `${baseUrl}/models/model-27.png?${cacheBuster}`, preview: `/models/model-27.png?${cacheBuster}`, name: "Daniela", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-18", url: `${baseUrl}/models/model-28.png?${cacheBuster}`, preview: `/models/model-28.png?${cacheBuster}`, name: "Delphin", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-19", url: `${baseUrl}/models/model-29.png?${cacheBuster}`, preview: `/models/model-29.png?${cacheBuster}`, name: "Diego", gender: "male", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-30", url: `${baseUrl}/models/model-40.png?${cacheBuster}`, preview: `/models/model-40.png?${cacheBuster}`, name: "Dion", gender: "male", ageGroup: "adult", ethnicity: "African" },
  { id: "model-20", url: `${baseUrl}/models/model-30.png?${cacheBuster}`, preview: `/models/model-30.png?${cacheBuster}`, name: "Elin", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-21", url: `${baseUrl}/models/model-31.png?${cacheBuster}`, preview: `/models/model-31.png?${cacheBuster}`, name: "Emanuel", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-22", url: `${baseUrl}/models/model-32.png?${cacheBuster}`, preview: `/models/model-32.png?${cacheBuster}`, name: "Emily", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-23", url: `${baseUrl}/models/model-33.png?${cacheBuster}`, preview: `/models/model-33.png?${cacheBuster}`, name: "Emma", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-24", url: `${baseUrl}/models/model-34.png?${cacheBuster}`, preview: `/models/model-34.png?${cacheBuster}`, name: "Ethan", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-25", url: `${baseUrl}/models/model-35.png?${cacheBuster}`, preview: `/models/model-35.png?${cacheBuster}`, name: "Eva", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-26", url: `${baseUrl}/models/model-36.png?${cacheBuster}`, preview: `/models/model-36.png?${cacheBuster}`, name: "Farah", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-27", url: `${baseUrl}/models/model-37.png?${cacheBuster}`, preview: `/models/model-37.png?${cacheBuster}`, name: "Farid", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-28", url: `${baseUrl}/models/model-38.png?${cacheBuster}`, preview: `/models/model-38.png?${cacheBuster}`, name: "Freya", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-29", url: `${baseUrl}/models/model-39.png?${cacheBuster}`, preview: `/models/model-39.png?${cacheBuster}`, name: "Gabriela", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-31", url: `${baseUrl}/models/model-41.png?${cacheBuster}`, preview: `/models/model-41.png?${cacheBuster}`, name: "Hamza", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-32", url: `${baseUrl}/models/model-42.png?${cacheBuster}`, preview: `/models/model-42.png?${cacheBuster}`, name: "Hanna", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-33", url: `${baseUrl}/models/model-43.png?${cacheBuster}`, preview: `/models/model-43.png?${cacheBuster}`, name: "Hassan", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-34", url: `${baseUrl}/models/model-44.png?${cacheBuster}`, preview: `/models/model-44.png?${cacheBuster}`, name: "Huda", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-35", url: `${baseUrl}/models/model-45.png?${cacheBuster}`, preview: `/models/model-45.png?${cacheBuster}`, name: "Iris", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-36", url: `${baseUrl}/models/model-46.png?${cacheBuster}`, preview: `/models/model-46.png?${cacheBuster}`, name: "Isabella", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-37", url: `${baseUrl}/models/model-47.png?${cacheBuster}`, preview: `/models/model-47.png?${cacheBuster}`, name: "Jasper", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-38", url: `${baseUrl}/models/model-48.png?${cacheBuster}`, preview: `/models/model-48.png?${cacheBuster}`, name: "Jemairo", gender: "male", ageGroup: "adult", ethnicity: "African" },
  { id: "model-39", url: `${baseUrl}/models/model-49.png?${cacheBuster}`, preview: `/models/model-49.png?${cacheBuster}`, name: "Joaquin", gender: "male", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-40", url: `${baseUrl}/models/model-50.png?${cacheBuster}`, preview: `/models/model-50.png?${cacheBuster}`, name: "Jordan", gender: "male", ageGroup: "adult", ethnicity: "Mixed" },
  { id: "model-96", url: `${baseUrl}/models/model-106.png?${cacheBuster}`, preview: `/models/model-106.png?${cacheBuster}`, name: "Julia", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-101", url: `${baseUrl}/models/model-111.png?${cacheBuster}`, preview: `/models/model-111.png?${cacheBuster}`, name: "Julian", gender: "male", ageGroup: "adult", ethnicity: "Mixed" },
  { id: "model-41", url: `${baseUrl}/models/model-51.png?${cacheBuster}`, preview: `/models/model-51.png?${cacheBuster}`, name: "Jun", gender: "male", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-42", url: `${baseUrl}/models/model-52.png?${cacheBuster}`, preview: `/models/model-52.png?${cacheBuster}`, name: "Justin", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-43", url: `${baseUrl}/models/model-53.png?${cacheBuster}`, preview: `/models/model-53.png?${cacheBuster}`, name: "Kai", gender: "male", ageGroup: "adult", ethnicity: "Mixed" },
  { id: "model-44", url: `${baseUrl}/models/model-54.png?${cacheBuster}`, preview: `/models/model-54.png?${cacheBuster}`, name: "Karam", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-45", url: `${baseUrl}/models/model-55.png?${cacheBuster}`, preview: `/models/model-55.png?${cacheBuster}`, name: "Karima", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-46", url: `${baseUrl}/models/model-56.png?${cacheBuster}`, preview: `/models/model-56.png?${cacheBuster}`, name: "Kevin", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-47", url: `${baseUrl}/models/model-57.png?${cacheBuster}`, preview: `/models/model-57.png?${cacheBuster}`, name: "Khalid", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-48", url: `${baseUrl}/models/model-58.png?${cacheBuster}`, preview: `/models/model-58.png?${cacheBuster}`, name: "Laura", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-49", url: `${baseUrl}/models/model-59.png?${cacheBuster}`, preview: `/models/model-59.png?${cacheBuster}`, name: "Layla", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-76", url: `${baseUrl}/models/model-86.png?${cacheBuster}`, preview: `/models/model-86.png?${cacheBuster}`, name: "Leila", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-50", url: `${baseUrl}/models/model-60.png?${cacheBuster}`, preview: `/models/model-60.png?${cacheBuster}`, name: "Liam", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-51", url: `${baseUrl}/models/model-61.png?${cacheBuster}`, preview: `/models/model-61.png?${cacheBuster}`, name: "Liang", gender: "male", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-52", url: `${baseUrl}/models/model-62.png?${cacheBuster}`, preview: `/models/model-62.png?${cacheBuster}`, name: "Lily", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-1", url: `${baseUrl}/models/model-1.png?${cacheBuster}`, preview: `/models/model-1.png?${cacheBuster}`, name: "Lin", gender: "female", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-53", url: `${baseUrl}/models/model-63.png?${cacheBuster}`, preview: `/models/model-63.png?${cacheBuster}`, name: "Lucas", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-94", url: `${baseUrl}/models/model-104.png?${cacheBuster}`, preview: `/models/model-104.png?${cacheBuster}`, name: "Lucia", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-54", url: `${baseUrl}/models/model-64.png?${cacheBuster}`, preview: `/models/model-64.png?${cacheBuster}`, name: "Luka", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-2", url: `${baseUrl}/models/model-2.png?${cacheBuster}`, preview: `/models/model-2.png?${cacheBuster}`, name: "Marcus", gender: "male", ageGroup: "adult", ethnicity: "African" },
  { id: "model-55", url: `${baseUrl}/models/model-65.png?${cacheBuster}`, preview: `/models/model-65.png?${cacheBuster}`, name: "Mariam", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-56", url: `${baseUrl}/models/model-66.png?${cacheBuster}`, preview: `/models/model-66.png?${cacheBuster}`, name: "Mason", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-57", url: `${baseUrl}/models/model-67.png?${cacheBuster}`, preview: `/models/model-67.png?${cacheBuster}`, name: "Mateo", gender: "male", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-58", url: `${baseUrl}/models/model-68.png?${cacheBuster}`, preview: `/models/model-68.png?${cacheBuster}`, name: "Mei", gender: "female", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-59", url: `${baseUrl}/models/model-69.png?${cacheBuster}`, preview: `/models/model-69.png?${cacheBuster}`, name: "Mia", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-60", url: `${baseUrl}/models/model-70.png?${cacheBuster}`, preview: `/models/model-70.png?${cacheBuster}`, name: "Mila", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-61", url: `${baseUrl}/models/model-71.png?${cacheBuster}`, preview: `/models/model-71.png?${cacheBuster}`, name: "Mitchel", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-62", url: `${baseUrl}/models/model-72.png?${cacheBuster}`, preview: `/models/model-72.png?${cacheBuster}`, name: "Nabil", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-97", url: `${baseUrl}/models/model-107.png?${cacheBuster}`, preview: `/models/model-107.png?${cacheBuster}`, name: "Natalia", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-63", url: `${baseUrl}/models/model-73.png?${cacheBuster}`, preview: `/models/model-73.png?${cacheBuster}`, name: "Nicolas", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-64", url: `${baseUrl}/models/model-74.png?${cacheBuster}`, preview: `/models/model-74.png?${cacheBuster}`, name: "Nina", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-65", url: `${baseUrl}/models/model-75.png?${cacheBuster}`, preview: `/models/model-75.png?${cacheBuster}`, name: "Noah", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-66", url: `${baseUrl}/models/model-76.png?${cacheBuster}`, preview: `/models/model-76.png?${cacheBuster}`, name: "Noor", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-67", url: `${baseUrl}/models/model-77.png?${cacheBuster}`, preview: `/models/model-77.png?${cacheBuster}`, name: "Nora", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-68", url: `${baseUrl}/models/model-78.png?${cacheBuster}`, preview: `/models/model-78.png?${cacheBuster}`, name: "Obinna", gender: "male", ageGroup: "adult", ethnicity: "African" },
  { id: "model-69", url: `${baseUrl}/models/model-79.png?${cacheBuster}`, preview: `/models/model-79.png?${cacheBuster}`, name: "Oliver", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-70", url: `${baseUrl}/models/model-80.png?${cacheBuster}`, preview: `/models/model-80.png?${cacheBuster}`, name: "Omar", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-71", url: `${baseUrl}/models/model-81.png?${cacheBuster}`, preview: `/models/model-81.png?${cacheBuster}`, name: "Owen", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-72", url: `${baseUrl}/models/model-82.png?${cacheBuster}`, preview: `/models/model-82.png?${cacheBuster}`, name: "Paul", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-73", url: `${baseUrl}/models/model-83.png?${cacheBuster}`, preview: `/models/model-83.png?${cacheBuster}`, name: "Peter", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-92", url: `${baseUrl}/models/model-102.png?${cacheBuster}`, preview: `/models/model-102.png?${cacheBuster}`, name: "Priya", gender: "female", ageGroup: "adult", ethnicity: "South Asian" },
  { id: "model-74", url: `${baseUrl}/models/model-84.png?${cacheBuster}`, preview: `/models/model-84.png?${cacheBuster}`, name: "Quintin", gender: "male", ageGroup: "adult", ethnicity: "Mixed" },
  { id: "model-75", url: `${baseUrl}/models/model-85.png?${cacheBuster}`, preview: `/models/model-85.png?${cacheBuster}`, name: "Rania", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-99", url: `${baseUrl}/models/model-109.png?${cacheBuster}`, preview: `/models/model-109.png?${cacheBuster}`, name: "Rosa", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-77", url: `${baseUrl}/models/model-87.png?${cacheBuster}`, preview: `/models/model-87.png?${cacheBuster}`, name: "Samira", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-78", url: `${baseUrl}/models/model-88.png?${cacheBuster}`, preview: `/models/model-88.png?${cacheBuster}`, name: "Santiago", gender: "male", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-98", url: `${baseUrl}/models/model-108.png?${cacheBuster}`, preview: `/models/model-108.png?${cacheBuster}`, name: "Sarah", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-79", url: `${baseUrl}/models/model-89.png?${cacheBuster}`, preview: `/models/model-89.png?${cacheBuster}`, name: "Shaq", gender: "male", ageGroup: "adult", ethnicity: "African" },
  { id: "model-9", url: `${baseUrl}/models/model-9.png?${cacheBuster}`, preview: `/models/model-9.png?${cacheBuster}`, name: "Sofia", gender: "female", ageGroup: "adult", ethnicity: "European" },
  { id: "model-80", url: `${baseUrl}/models/model-90.png?${cacheBuster}`, preview: `/models/model-90.png?${cacheBuster}`, name: "Tarek", gender: "male", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-81", url: `${baseUrl}/models/model-91.png?${cacheBuster}`, preview: `/models/model-91.png?${cacheBuster}`, name: "Tijn", gender: "male", ageGroup: "adult", ethnicity: "European" },
  { id: "model-82", url: `${baseUrl}/models/model-92.png?${cacheBuster}`, preview: `/models/model-92.png?${cacheBuster}`, name: "Valentina", gender: "female", ageGroup: "adult", ethnicity: "Latin American" },
  { id: "model-83", url: `${baseUrl}/models/model-93.png?${cacheBuster}`, preview: `/models/model-93.png?${cacheBuster}`, name: "Xia", gender: "female", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-84", url: `${baseUrl}/models/model-94.png?${cacheBuster}`, preview: `/models/model-94.png?${cacheBuster}`, name: "Yasmin", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-85", url: `${baseUrl}/models/model-95.png?${cacheBuster}`, preview: `/models/model-95.png?${cacheBuster}`, name: "Ying", gender: "female", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-86", url: `${baseUrl}/models/model-96.png?${cacheBuster}`, preview: `/models/model-96.png?${cacheBuster}`, name: "Yu", gender: "male", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-87", url: `${baseUrl}/models/model-97.png?${cacheBuster}`, preview: `/models/model-97.png?${cacheBuster}`, name: "Yuki", gender: "female", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-88", url: `${baseUrl}/models/model-98.png?${cacheBuster}`, preview: `/models/model-98.png?${cacheBuster}`, name: "Yuta", gender: "male", ageGroup: "adult", ethnicity: "East Asian" },
  { id: "model-89", url: `${baseUrl}/models/model-99.png?${cacheBuster}`, preview: `/models/model-99.png?${cacheBuster}`, name: "Zahra", gender: "female", ageGroup: "adult", ethnicity: "Middle Eastern" },
  { id: "model-90", url: `${baseUrl}/models/model-100.png?${cacheBuster}`, preview: `/models/model-100.png?${cacheBuster}`, name: "Zoe", gender: "female", ageGroup: "adult", ethnicity: "European" },
];
