INSERT INTO public.default_models (name, image_url, gender, ethnicity, is_active, sort_order) VALUES
('Clara', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Clara-3.png', 'female', 'European', true, 220),
('Daniela', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Daniela-3.png', 'female', 'Latin American', true, 221),
('Delphin', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Delphin-3.png', 'male', 'African', true, 222),
('Diego', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Diego-3.png', 'male', 'Latin American', true, 223),
('Dion', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Dion-5.png', 'male', 'African', true, 224),
('Elin', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Elin-2.png', 'female', 'European', true, 225),
('Emanuel', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Emanuel-2.png', 'male', 'African', true, 226),
('Emily', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Emily-2.png', 'female', 'European', true, 227),
('Emma', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Emma-2.png', 'female', 'European', true, 228),
('Ethan', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Ethan-2.png', 'male', 'South Asian', true, 229),
('Eva', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Eva-2.png', 'female', 'European', true, 230),
('Farah', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Farah-2.png', 'female', 'Mixed', true, 231),
('Farid', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Farid-2.png', 'male', 'Latin American', true, 232),
('Freya', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Freya-2.png', 'female', 'Latin American', true, 233),
('Gabriela', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Gabriela-2.png', 'female', 'Middle Eastern', true, 234),
('Hamza', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Hamza-2.png', 'male', 'Middle Eastern', true, 235),
('Hanna', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Hanna-2.png', 'female', 'European', true, 236),
('Hassan', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Hassan-2.png', 'male', 'South Asian', true, 237),
('Huda', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Huda-2.png', 'female', 'Southeast Asian', true, 238),
('Iris', 'https://fjzifykgvdsownlscgct.supabase.co/storage/v1/object/public/products/default-models/Iris-2.png', 'female', 'African', true, 239);